// Code generated by erpgen v0.0.0-dev. DO NOT EDIT.

package bank_account_rest

import (
	context "context"
	dto "erp/api/dto"
	"erp/internal/app/service/helpers"
	"erp/internal/domain"
	"erp/internal/domain/repository"
	"net/http"

	"github.com/danielgtaylor/huma/v2"
	bank_account_domain "erp/project/accounting/banking/bank_account/domain"
)

type handler struct {
	sessionHelper helpers.SessionHelper
	locale        helpers.Locale
	errorHelper   helpers.ErrorHelper
	permission    repository.PermissionService
	usecase       bank_account_domain.UseCase
}

func NewHandler(
	api huma.API,
	helpers *helpers.Helpers,
	middlewares huma.Middlewares,
	permission repository.PermissionService,
	usecase bank_account_domain.UseCase,
) {
	base := domain.BANK_ACCOUNT_ROUTE
	tags := []string{"Bank Account"}
	h := handler{
		sessionHelper: helpers.Session,
		locale:        helpers.Locale,
		errorHelper:   helpers.Error,
		usecase:       usecase,
		permission:    permission,
	}

	huma.Register(api, huma.Operation{
		OperationID:   "bank-account",
		Method:        http.MethodGet,
		Summary:       "Bank Account",
		Tags:          tags,
		Path:          base,
		DefaultStatus: http.StatusOK,
		Middlewares:   middlewares,
	}, h.GetList)
	huma.Register(api, huma.Operation{
		OperationID:   "bank-account-detail",
		Method:        http.MethodGet,
		Summary:       "Bank Account Detail",
		Tags:          tags,
		Path:          base + "/detail/{id}",
		DefaultStatus: http.StatusOK,
		Middlewares:   middlewares,
	}, h.Get)

	huma.Register(api, huma.Operation{
		OperationID:   "create-bank-account",
		Method:        http.MethodPost,
		Summary:       "Create Bank Account",
		Tags:          tags,
		Path:          base,
		DefaultStatus: http.StatusCreated,
		Middlewares:   middlewares,
	}, h.Create)

	huma.Register(api, huma.Operation{
		OperationID:   "edit-bank_account",
		Method:        http.MethodPut,
		Path:          base,
		Summary:       "Edit Bank Account",
		Tags:          tags,
		DefaultStatus: http.StatusOK,
		Middlewares:   middlewares,
	}, h.Edit)

	huma.Register(api, huma.Operation{
		OperationID:   "update-status-bank-account",
		Method:        http.MethodPut,
		Path:          base + "/update-status",
		Summary:       "Update Status Bank Account",
		Tags:          tags,
		DefaultStatus: http.StatusOK,
		Middlewares:   middlewares,
	}, h.UpdateStatus)
}

// Create provides a function with given fields: ctx, d

func (m *handler) Create(ctx context.Context, d *dto.BankAccountDataRequest) (_a0 *dto.ResponseData[dto.BankAccountDto], _a1 error) {

	req, err := m.sessionHelper.GetSession(ctx)
	if err != nil {
		return nil, huma.Error400BadRequest("Not Authorized", err)
	}
	res, err := m.usecase.Create(req, d.Body)
	if err != nil {
		return nil, m.errorHelper.HumaCustomError(string(req.LanguageCode), err, "Error.FailToCreate")
	}
	var response dto.ResponseData[dto.BankAccountDto]
	response.Body.Result = res
	response.Body.Message = m.locale.MustLocalize(
		helpers.OptionsLocale.WithID("Message.CreatedSuccessfully"),
		helpers.OptionsLocale.WithLang(string(req.LanguageCode)),
	)
	return &response, nil

}

// Edit provides a function with given fields: ctx, d

func (m *handler) Edit(ctx context.Context, d *dto.BankAccountDataRequest) (_a0 *dto.ResponseMessage, _a1 error) {

	req, err := m.sessionHelper.GetSession(ctx)
	if err != nil {
		return nil, huma.Error400BadRequest("Not Authorized", err)
	}
	err = m.usecase.Edit(req, d.Body)
	if err != nil {
		return nil, m.errorHelper.HumaCustomError(string(req.LanguageCode), err, "Error.FailToEdit")
	}
	var response dto.ResponseMessage
	response.Body.Message = m.locale.MustLocalize(
		helpers.OptionsLocale.WithID("Message.EditedSuccessfully"),
		helpers.OptionsLocale.WithLang(string(req.LanguageCode)),
	)
	return &response, nil

}

// Get provides a function with given fields: ctx, d

func (m *handler) Get(ctx context.Context, d *dto.RequestEntity) (_a0 *dto.EntityResponse[dto.ResultEntity[dto.BankAccountDto]], _a1 error) {

	req, err := m.sessionHelper.GetSession(ctx)
	if err != nil {
		return nil, huma.Error400BadRequest("Not Authorized", err)
	}
	res, err := m.usecase.Get(req, *d)
	if err != nil {
		return nil, m.errorHelper.HumaCustomError(string(req.LanguageCode), err)
	}
	var response dto.EntityResponse[dto.ResultEntity[dto.BankAccountDto]]
	response.Body.Result = res
	response.Body.Actions = m.permission.GetActions(req.Ctx, domain.BANK_ACCOUNT.ID)
	return &response, nil

}

// GetList provides a function with given fields: ctx, d

func (m *handler) GetList(ctx context.Context, d *dto.BankAccountsRequest) (_a0 *dto.ResponseDataList[[]dto.BankAccountDto], _a1 error) {

	req, err := m.sessionHelper.GetSession(ctx)
	if err != nil {
		return nil, huma.Error400BadRequest("Not Authorized", err)
	}
	res, err := m.usecase.GetList(req, *d)
	if err != nil {
		return nil, m.errorHelper.HumaCustomError(string(req.LanguageCode), err)
	}
	res.Body.Actions = m.permission.GetActions(req.Ctx, domain.BANK_ACCOUNT.ID)
	return &res, nil

}

// UpdateStatus provides a function with given fields: ctx, d

func (m *handler) UpdateStatus(ctx context.Context, d *dto.UpdateStatusWithEvent) (_a0 *dto.ResponseMessage, _a1 error) {

	req, err := m.sessionHelper.GetSession(ctx)
	if err != nil {
		return nil, huma.Error400BadRequest("Not Authorized", err)
	}
	err = m.usecase.UpdateStatus(req, d)
	if err != nil {
		return nil, m.errorHelper.HumaCustomError(string(req.LanguageCode), err, "Error.FailToUpdate")
	}
	var response dto.ResponseMessage
	response.Body.Message = m.locale.MustLocalize(
		helpers.OptionsLocale.WithID("Message.UpdatedSuccessfully"),
		helpers.OptionsLocale.WithLang(string(req.LanguageCode)),
	)
	return &response, nil

}
