@startuml
namespace invoice_ucase {
    interface InvoiceUseCase  {
        + CreateInvoice(req *common.RequestContext, i dto.InvoiceBody) (dto.InvoiceDto, error)
        + GetInvoices(req *common.RequestContext, i *dto.RequestInvoices) (, error)
        + GetInvoiceDetail(req *common.RequestContext, d *dto.RequestEntityWithParty) (, error)
        + UpdateInvoiceState(req *common.RequestContext, d *dto.UpdateStatusWithEvent) error
        + EditInvoice(req *common.RequestContext, d dto.InvoiceBody) error
        + GetEntityInvoice(partyCode string) (domain.EntityTemplate, error)

    }
    class invoiceUseCase << (S,Aquamarine) >> {
        - invoiceRepository repository.InvoiceRepository
        - emitLog logger.EmitLog
        - permissionService repository.PermissionService
        - invoiceFsm fsm.FsmState
        - bus bus.Bus
        - c di.Container
        - core repository.CoreService
        - stock repository.StockService

        - closeTx(tx *query.QueryTx, err error) error

        + UpdateInvoiceState(req *common.RequestContext, i *dto.UpdateStatusWithEvent) error
        + EditInvoice(req *common.RequestContext, d dto.InvoiceBody) error
        + GetInvoiceDetail(req *common.RequestContext, i *dto.RequestEntityWithParty) (, error)
        + GetInvoices(req *common.RequestContext, i *dto.RequestInvoices) (, error)
        + CreateInvoice(req *common.RequestContext, i dto.InvoiceBody) (dto.InvoiceDto, error)
        + GetEntityInvoice(partyCode string) (domain.EntityTemplate, error)

    }
}

"invoice_ucase.InvoiceUseCase" <|-- "invoice_ucase.invoiceUseCase"

@enduml
