// Code generated by erpgen v0.0.0-dev. DO NOT EDIT.

package bank_account_usecase

import (
	common "erp/api/common"
	dto "erp/api/dto"
	"erp/internal/domain"
	"erp/internal/domain/repository"
	"erp/pkg/fsm"
	"erp/pkg/logger"
	bank_account_domain "erp/project/accounting/banking/bank_account/domain"
)

type useCase struct {
	emitLog    logger.EmitLog
	core       repository.CoreService
	permission repository.PermissionService
	repo       bank_account_domain.Repository
	fsm        fsm.FsmState
}

func NewUseCase(
	logger logger.Logger,
	core repository.CoreService,
	permission repository.PermissionService,
	repo bank_account_domain.Repository,
	fsm fsm.FsmState,
) bank_account_domain.UseCase {
	return &useCase{
		emitLog:    logger.EmitLog("bank_account-ucase"),
		core:       core,
		permission: permission,
		fsm:        fsm,
		repo:       repo,
	}
}

// Create provides a function with given fields: req, d

func (m *useCase) Create(req *common.RequestContext, d dto.BankAccountData) (res dto.BankAccountDto, err error) {

	defer func() {
		if err != nil {
			m.emitLog.Err(err, logger.OptionsLog.WithMethod("Create"))
		}
	}()

	if err := m.permission.CheckPermissionEntity(req.Ctx, req, domain.BANK_ACCOUNT, domain.CREATE); err != nil {
		return res, err
	}
	entityModel, err := m.repo.Create(req, d)
	if err != nil {
		return
	}
	res = dto.BankAccountFromModel(entityModel)

	return

}

// Edit provides a function with given fields: req, d

func (m *useCase) Edit(req *common.RequestContext, d dto.BankAccountData) (err error) {

	defer func() {
		if err != nil {
			m.emitLog.Err(err, logger.OptionsLog.WithMethod("Edit"))
		}
	}()

	if err := m.permission.CheckPermissionEntity(req.Ctx, req, domain.BANK_ACCOUNT, domain.EDIT); err != nil {
		return err
	}
	err = m.repo.Edit(req, d)

	return

}

// Get provides a function with given fields: req, d

func (m *useCase) Get(req *common.RequestContext, d dto.RequestEntity) (res dto.ResultEntity[dto.BankAccountDto], err error) {

	defer func() {
		if err != nil {
			m.emitLog.Err(err, logger.OptionsLog.WithMethod("Get"))
		}
	}()

	if err := m.permission.CheckPermissionEntity(req.Ctx, req, domain.BANK_ACCOUNT, domain.VIEW); err != nil {
		return res, err
	}
	res.Entity, err = m.repo.Get(req, d)
	if err != nil {
		return
	}
	res.Activities = m.core.GerActivitiesByPartyID(req, res.Entity.ID)

	return

}

// GetList provides a function with given fields: req, d

func (m *useCase) GetList(req *common.RequestContext, d dto.BankAccountsRequest) (res dto.ResponseDataList[[]dto.BankAccountDto], err error) {

	defer func() {
		if err != nil {
			m.emitLog.Err(err, logger.OptionsLog.WithMethod("GetList"))
		}
	}()

	if err := m.permission.CheckPermissionEntity(req.Ctx, req, domain.BANK_ACCOUNT, domain.VIEW); err != nil {
		return res, err
	}
	res.Body.Result, err = m.repo.GetList(req, d)
	if err != nil {
		return
	}
	res.Body.FilterOptions = m.repo.GetFilterOptions(string(req.LanguageCode))

	return

}

// UpdateStatus provides a function with given fields: req, d

func (m *useCase) UpdateStatus(req *common.RequestContext, d *dto.UpdateStatusWithEvent) (err error) {

	defer func() {
		if err != nil {
			m.emitLog.Err(err, logger.OptionsLog.WithMethod("UpdateStatus"))
		}
	}()

	if err := m.permission.CheckPermissionEntity(req.Ctx, req, domain.PAYMENT_TERMS, domain.EDIT); err != nil {
		return err
	}
	nextState, err := m.fsm.NextState(d.Body.CurrentState, d.Body.Events)
	if err != nil {
		return err
	}
	err = m.repo.UpdateStatus(req, d, nextState)

	return

}
