// Code generated by erpgen v0.0.0-dev. DO NOT EDIT.

package bank_repo

import (
	common "erp/api/common"
	"erp/internal/app/service/helpers"
	"erp/pkg/db"
	bank_domain "erp/project/accounting/banking/bank/domain"

	dto "erp/api/dto"

	model "erp/gen/db/model"

	"erp/gen/db/query"
	"erp/gen/proto"
)

type repository struct {
	convertor helpers.ConvertorHelper
	Q         *query.Query
	query     helpers.QueryHelper
}

func NewRepository(
	conn db.Connection,
	helpers *helpers.Helpers,
) bank_domain.Repository {

	return &repository{
		convertor: helpers.Convertor,
		Q:         conn.GetQ(),
		query:     helpers.Query,
	}
}

// Create provides a function with given fields: req, d

func (m *repository) Create(req *common.RequestContext, d dto.BankData) (res model.Bank, err error) {

	tx := m.Q.Begin()
	defer func() {
		if err != nil {
			tx.Rollback()
		}
	}()

	id, err := tx.Bank.InsertParty(proto.PartyType_bank.String())
	if err != nil {
		return
	}
	fields := d.Fields
	res.ID = id
	res.CompanyID = req.ActiveCompany.ID
	res.Status = proto.State_ENABLED.String()
	if err = m.convertor.CopyStructData(fields, &res); err != nil {
		return
	}
	err = tx.WithContext(req.Ctx).Bank.Save(&res)
	if err != nil {
		return
	}
	if err = tx.Invoice.InsertActivity(id, req.Profile.ID, proto.ActivityType_CREATE.String(), nil); err != nil {
		return
	}

	err = tx.Commit()

	return

}

// Edit provides a function with given fields: req, d

func (m *repository) Edit(req *common.RequestContext, d dto.BankData) (err error) {

	tx := m.Q.Begin()
	defer func() {
		if err != nil {
			tx.Rollback()
		}
	}()

	data, err := m.convertor.DataMap(d.Fields)
	if err != nil {
		return
	}
	err = tx.Bank.UnderlyingDB().WithContext(req.Ctx).Model(
		&model.Bank{ID: d.ID},
	).Updates(data).Error
	if err != nil {
		return
	}
	err = tx.Bank.InsertActivity(d.ID, req.Profile.ID, proto.ActivityType_EDIT.String(), nil)
	if err != nil {
		return
	}

	err = tx.Commit()

	return

}

// UpdateStatus provides a function with given fields: req, d, nextState

func (m *repository) UpdateStatus(req *common.RequestContext, d *dto.UpdateStatusWithEvent, nextState string) (err error) {

	qI := m.Q.Bank
	_, err = m.Q.Bank.WithContext(req.Ctx).Where(
		qI.CompanyID.Eq(req.ActiveCompany.ID),
		qI.Status.Eq(d.Body.CurrentState),
		qI.UUID.Eq(d.Body.PartyID),
	).UpdateSimple(
		qI.Status.Value(nextState),
	)

	return

}
